### PR TITLE
add font awesome and style changes to root

### PR DESCRIPTION
**Pull request by mollybrown**
This PR adds the Font Awesome CDN and tweaks to the Bootstrap styles and CSS. Design follows wireframes designed by @robsedivy.

### CODE REVIEW

**Comment by ScorchConway** [comment]
This looks great!  I know Andrew (AndrewF on flowdock) worked on styling last week.  The home page also I think.   Maybe the two of you could reconcile what you've worked on so far.

**Comment by AndrewKF** [comment]
This looks good @mollybrown! I have some changes as well to this page (mostly in the map area and navigation). Do we want to merge this branch in?

**Comment by mollybrown** [comment]
@AndrewKF Go ahead and merge! Feel free to add any of the changes you've got as well :)

**Comment by chompasina** [comment]
Looks good to me! 👍

**Pull request merged**
