### PR TITLE
268 cypress tests

### PR DESCRIPTION
**Pull request by dwhite96**
Add "Why Recycle" test. Also changed the filename to ```landing_page_spec.js``` to match the page features being tested.

### CODE REVIEW

**Comment by hoop71** [comment]
So this looks like Travis failed because it couldn't get to the test.js file on the backend now that it's in .gitignore. This seems ok to me but we might consider how we want to do this moving forward.

**Comment by dwhite96** [comment]
I assume Travis CI runs the cypress tests in the staging environment as part of the continuous integration so does that mean that we need to add environment variables in the test.js file for the credentials and then remove this file from .gitignore?

**Comment by ximsce** [comment]
I believe the travis ci build runs in a local test environment, not the staging environment. It is supposed to have its own set of properties (through test.js?) to set that all up.

**Comment by dwhite96** [comment]
I just made a new commit that changes the test.js file back to the original from the master branch and removed it from .gitignore. The current tests pass in my local environment without any api keys. I wanted to see if it would pass in Travis this way.

**Pull request merged**
