### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by dkoloditch**
This resolves the failure of `npm install` and `npm install npm-run-all` on the initial `docker-compose up`. The error was encountered after attempting to run `rake start` via the command field in `docker-compose.yml`.

When testing, make sure you shut down all other applications running on ports 3000 and 3001, then remove any previous container and image(s):
- `docker rm circular_web_1`
- `docker rm circular_db_1`
- `docker rmi circular_web`

### CODE REVIEW

**Comment by chompasina** [comment]
Nice work! We're so excited that you all are working on this. I have Docker on my machine already and would like to pull down this branch before we merge it. I'll try to do that by Thursday Hack night if you don't mind holding off on merging. :)

**Comment by dkoloditch** [comment]
Thanks! Please test heavily. Definitely no rush. I may have jumped the gun asking to get this into master, so I'm certainly willing to push the changes to the CfD docker branch instead.

**Comment by dannyradden** [comment]
Now obsolete with new backend

**Comment by chompasina** [comment]
(Might be easier to try fresh off new master since we switched to Node. Sorry @dkoloditch ! This would be pretty neat if you wanted to try again.)

**Comment by dkoloditch** [comment]
No problem whatsoever, @chompasina! I'll take a crack at it if and when I get some time.

**Pull request closed without merging**
