### PR TITLE
Change Link to FAQ page on Why NavBar Link (#302)

### PR DESCRIPTION
**Pull request by marshallhouston**
This PR changes the link on the Why NavBar link to /denver-learn-more (#302).

The About component is no longer used, and it was deleted.

Multiple other components used styling from _About.scss, so to more clearly represent this usage, I changed it to to a partial _info. References to "about" in classNames have now been changed to "info".

### CODE REVIEW

**Comment by marshallhouston** [comment]
@hoop71 

I agree with you about the conventions. I added the underscore because it looks like _form and _button are used across multiple components in the same way that _info is used. 

At first glance, the components that do not use an underscore seem to refer to one specific component.

I would need to spend more time seeing if that pattern holds true (I imagine it doesn't).

**Comment by TheBrooks** [comment]
Looks good.  Squash and Merge please

**Comment by marshallhouston** [comment]
On previous teams, I’ve always followed the pattern that another person on the team merges the PR into master.

If that’s not the process we're following, I can squash and merge since the changes are approved and checks are passed.

**Comment by TheBrooks** [comment]
Go ahead and so the deed.  you know best how to comment the squash commit message.  
Also add 'Connect #302' in your message to have the waffle board auto update

**Pull request merged**
