### PR TITLE
Choose campaign

### LINKED ISSUE #128: Style out the choose-campaign page
As a user, 
when I enter my address, 
I am taken to a page with a list of nearby campaigns. I can select the radio button for my address, or I can select 'None, create a new campaign'. 

Expected outcome: 
This page's route is already built, but is not styled at all, so needs to incorporate styling. The closest campaign should have the radio button selected already.

### PR DESCRIPTION
**Pull request by AndrewKF**
This branch is to display campaign search results for when a user is finding a campaign to join or to start. These changes are to resolve #128 Style out the choose-campaign page.

As we don't have styling robustly defined yet I think it would be good to review the interaction of selecting a campaign and see if makes sense for this component.

### CODE REVIEW

**Comment by chompasina** [comment]
Yeah @AndrewKF ! Way to go! I want to pull this down at lunch and review, so I'll get you feedback and hopefully we can merge today. :)

**Comment by AndrewKF** [comment]
Merged some css changes from Master to keep it up to date 👍

**Comment by ximsce** [comment]
Hey, there are a couple css errors that I can push fixes to the branch, but I don't know how to test this page since as far as I can tell the search functionality isn't bringing up existing campaigns. Any word on if that is supposed to be working?

**Comment by AndrewKF** [comment]
Thanks for looking over the branch @ximsce! I merged without noticing the `;` and `}` updates from another branch.

As far was the search results go, the issue maybe that the searched address needs to be near the addresses in the seeds.rb file for results to show up. This file is located in `/db/seeds.rb` and a search for, or near, any of those addresses should bring back results.

**Comment by chompasina** [comment]
@ximsce to load seed file, run `rake db:seed` --I haven't run them myself though but that should do it. :) Also, I'm about to pull this down and check it out too. Sorry for my terrible delays with this!!

**Comment by ximsce** [comment]
So, for the functionality to work we have to load those seeds? Shouldn't
the search be able to pick up new addresses/campaigns? Or is someone still
working on that?

**Comment by AndrewKF** [comment]
I believe someone is still working on the functionality to create campaigns. The story for this waffle card was to style out the results that are retuned. 

From waffle card 128:
> This page's route is already built, but is not styled at all, so needs to incorporate styling. The closest campaign should have the radio button selected already.

If this merge should wait until we have that functionality further developed let me know I can pull the PR.

**Comment by ximsce** [comment]
Nope, if the functionality you are working on looks good and someone else
has reviewed go ahead and merge. I'm just on-call and cranky

**Pull request merged**
