### PR TITLE
384 firestore db rules

### PR DESCRIPTION
**Pull request by dwhite96**

### CODE REVIEW

**Comment by hoop71** [comment]
@dwhite96 Did you want to take look at this failing tests or should we give this out to someone else?

**Comment by dwhite96** [comment]
Yeah, I'll take a look at that tomorrow night.

**Comment by dwhite96** [comment]
It passed with a simple build restart.

**Comment by hoop71** [comment]
Let's get some tests on these and we will be ready to merge it in!

**Comment by dwhite96** [comment]
Okay

**Comment by JasminBarco** [comment]
We need JEST to do these tests, almost there!

**Pull request closed without merging**
